### ISSUE TITLE
El nombre del archivo de cron.d no debería terminar en .cron

### ISSUE THREAD

**Issue by MauricioAcosta** [JorgeUlises/scripts_utiles#1]
En la versión de cron:
cron/trusty,now 3.0pl1-124ubuntu2 amd64 [installed]
No reconoce los scripts con esta extensión. Al removerla carga correctamente.

**Comment by juusechec** [comment]
Se corrige mediante el commit https://github.com/juusechec/scripts_utiles/commit/00667c6cb123f08acd5e3a0ff82aeead31aac617
